### ISSUE TITLE
Clarification of start index and end index?

### ISSUE THREAD

**Issue by robotictacos** [haberda/update_lights#4]
Hi There,
First thanks for your work.  Second, I don't understand how the start index and end index are used in a practical sense, can you give an example of how they would function in an automation?  I see in your docs that you give an example of two times that can be given, but what would be the impact in that case?

I think this app might fit my use case, but I'm just not sure how I'd deploy it.  For my use case, I'd like my lights to go to full brightness at, let's say 5pm then dim to the minimum level at 10pm.  Then I want to have those lights resume the minimum level at 6am, coming back up to full brightness at 10am.  I'm pretty sure your app does this, but I think the variables and how they are used are confusing me.

Thanks

**Comment by haberda** [comment]
It's a little hard to explain but I'll try my best.

Ok, so if you imagine the simple case of a start and end time you would end up will a bell curve where the peak of the curve (point of minimum brightness) occurs exactly in the middle of the start and end time.

If you set a start index you will end up with two curves that overlap. What it will do is replace the start time with the index time and calculate a curve in between the start index time and the end time. Keep in mind, outside of the start and end times we are at 100% brightness no matter what the curve is doing, but with setting a start index (assuming it's earlier than the start time) as soon as we enter the start->end time window the brightness will step down because the tail of the curve between the start index and end time starts earlier than the start time.

The reason I implemented this was simply that I found my lights to be too bright by the time I wanted to go to bed. By setting a start index the lights get dimmer earlier. The nice thing about this is you can have the period where the lights are actively being adjusted (regular start and end times) set to sunset->sunrise, but have indexes set based on absolute time. So no matter what time of the year, you will have a similar brightness at any given time. 

The end index works the same way but on the other side. So if you set the end index later it will use the start time (not start index) and end index to calculate brightness. Once again this is used to make it so the lights are not so bright in the morning, but also have it so as soon as we are outside of the end time we jump to max brightness.

What is not handled well currently is what happens near the midpoint of the night when an index is set. If you have, let's say a start index set, and you were to watch the light you would see it get dimmer until we hit the mid point between the start index and end time, then it would start to get brighter. However, as soon as we hit the real midpoint between the start and end times it will dim again and then start to get brighter again. So it's not perfect and in my case this happens in the middle of the night when everyone is sleeping (also why I have sleep entity).

To answer your question more directly, it would be sort of possible to do what you are suggesting but the lights will start to get bright after 10 pm until we hit the 'real midpoint' between the start and end time at which point they will suddenly drop in brightness and then dim to the minimum point (6am). Also what you want to do would require setting a start and end index that overlap, I wrote the code some time ago so it may not be handled well and I honestly don't know what would happen. 

Keep in mind that the start index uses the end time to calculate the midpoint and the end index uses the start time. I think what you want might work if you set:

start time: 5pm
end time: 10am
start index: 12 noon
end index: 6pm

To suppress any weirdness in the middle of the night you could use an input boolean to keep the lights at min brightness using the sleep entity.

Also, you can experiment by setting the sensor log option and observing what the curves look like the next morning. 

All that said, what I suggest is this: use two separate instances of the app rather then indexes. Because AppDaemon allows you to run the same app many times and with different conditions, to get exactly what you want I would just use two separate instances where you do not use the indexes at all. The app can be disabled with the disable_entity key what you provide an input boolean, you can use the same boolean and set one to use the on condition and one to use the off condition. This way you can simply set the first app:

start time: 5pm
end time: 3am

to get the minimum brightness at 10pm, and:

start time: 2am
end time: 10am

to get minimum at 6am.

Here would be a minimum working config for the two instances:
```
evening_light:
  module: update_lights
  class: update_lights
  entities:
    - light.my_light
  start_time: '17:00:00'
  end_time: '03:00:00'
  disable_entity: 
    - input_boolean.my_bool,on

morning_light:
  module: update_lights
  class: update_lights
  entities:
    - light.my_light
  start_time: '02:00:00'
  end_time: '10:00:00'
  disable_entity: 
    - input_boolean.my_bool,off
```
I would also use the sleep entity to keep the lights dim no mater what during the night because as the lights will be near 100% brightness at 2am. Some other automation can switch on/off the my_bool boolean and the sleep entity if you choose to use it.

Anyway, sorry for so much text, hopefully it's a little more clear.

**Comment by robotictacos** [comment]
This is an amazing reply, fantastic detail. I will try the two instance approach starting tomorrow and report back.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
