### ISSUE TITLE
Turns of Lights but never adjusts them

### ISSUE THREAD

**Issue by jamiewalters** [haberda/update_lights#6]
I am running this script on appdaemon 4.0.5 and HA 0.115. It successfully turns on the lights as expected, however they never adjust as expected.

apps.yaml:
module: update_lights
  class: update_lights
  entities:
    - light.fasad
  max_brightness_level: 50
  min_brightness_level: 10
  run_every: 30
  start_time: '09:18:00'
  end_time: '10:00:00'
  start_lights_on: true

appdaemon:
`fasad_update_lights | 2020-10-05T09:18:00+02:00 | 1 day, 0:00:00 | lights_on | 1 | 1 | true | 0 | {"interval":86400}
fasad_update_lights | 2020-10-04T09:33:47+02:00 | 0:00:30 | time_change | 31 | 31 | true | 0 | {"interval":30}`

I see no errors in the logs using the appdaemon ui.

I do however notice one thing: the lights are 49 on turn on however they are set at 50.

**Comment by haberda** [comment]
I will try and run your config and see what the problem is, but the main problem might the max and min brightness and the shortness of time you have. Do you expect it to turn on to 50% or 50 bits (given a bit range from 0-255)? This config as you presented it is in bit, so 50 is about 20% brightness and 10 is 4%.

Also, when you hit the start time it will start to dim, so the smallest value it can subtract would be 1 bit, hence the 49. Think of it as max brightness will only occur before the start time. So this part is working as intended.

**Comment by haberda** [comment]
Ok, I copied your config and the only thing I changed was the light name and the time so that it was close to the current time. The start->end window was still only 42 minutes as your config is. As far as I can tell it worked fine. It started at 50 before the start time, went to 10 in the middle of the start to end, then came back up to 50. I am not sure what else to try. 

Just asking because maybe it is a simple mistake, did you mean to only make it 42 minutes? Or did you mean '09:18' to be '21:18'?

**Comment by jamiewalters** [comment]
thanks for the quick reply.

So i tried this again:

  module: update_lights
  class: update_lights
  entities:
    - light.living_room_sofa
  max_brightness_level: 200
  min_brightness_level: 10
  run_every: 30
  start_time: '17:53:00'
  end_time: '00:00:00'
  start_lights_on: true

at 18:50, it looks like this:

brightness: 201
node_id: 10
friendly_name: Living Room Sofa
supported_features: 33

I was expecting it to change a few bits within an hour, or am  i missing something?
It starts the light as expected.
According to appdaemon it was fired 121 times since it started.

I notice this time it started at 201 when it was set to 200, i assume your code is expecting to find it at 200, sees 201 and assumes it was manually adjusted and hopped over it. Question is how did it become 201?

**Comment by jamiewalters** [comment]
i notice that if i change the brightness manually, then after 30s (the run_every) it sets it back to the max_brightness_level

**Comment by haberda** [comment]
That is quite odd, it should be around 160 at the time you mentioned. I am not sure what is wrong. I suggest you use the sensor log option in the documentation to see what is going on. It will create a sensor in Home Assistant with the current dim level (aka 1-brightness). It will update each time the app runs. You can also use the event subscription to trigger it at will. I tried this configuration in my setup and it works fine.

A couple questions to consider:
- I noticed that in your configuration, both times, you do not have an app name. Without an app name app-daemon will do funny things. Here is what I mean (where app_name can be anything):
```
app_name:
  module: update_lights
  class: update_lights
  entities:
    - light.living_room_sofa
  max_brightness_level: 200
  min_brightness_level: 10
  run_every: 30
  start_time: '17:53:00'
  end_time: '00:00:00'
  start_lights_on: true
```
- Is this light handled by more than one update_lights configuration? If so they will fight each other. The app runs 24 hours and outside of the start/end time it just uses max brightness. You can have one light managed by multiple configurations but you should use the disable_entity feature to handle that.

**Comment by jamiewalters** [comment]
I see the sensor is reporting this:


state: -405.11341671834043
unit_of_measurement: % 
note: Percentage of dimming, inverted to brightness percent

seems a little odd -405% or?

**Comment by haberda** [comment]
Yeah, that makes no sense. I really am not sure what else to try, I cannot reproduce your issue and the way it's behaving doesn't make sense. If you are able to troubleshoot and figure it out, let me know.
